### ISSUE TITLE
Errors when installing pipenv (pycrypto dependency)

### ISSUE THREAD

**Issue by gingerbeardman** [ewdurbin/evacuate_2stp#3]
> I am forcing python 3.7 (by editing the Pipfile) as that is what I got from brew installing python 3, and I do not know how to install 3.6 specifically.

all goes well until `pycrypto`, at which time there were reams of error messages:
https://pastebin.com/raw/UjRHQ9Ca

so I did a manual `pip install pycrypto`, which went OK:
https://pastebin.com/raw/1TMb01db

So any ideas how I can proceed using `pipenv`?

macOS 10.13.6 (17G4015)

**Comment by gingerbeardman** [comment]
Found a workaround to install dependencies outside of pipenv

https://github.com/pypa/pipenv/issues/1356#issuecomment-446458444

```
pipenv lock --requirements > requirements.txt
pip install -r requirements.txt
```

and I could then run it

`python decrypt_2STP.py --encrypted-2stp-export demo.2stp`

**Comment by techalchemy** [comment]
Hey there -- pipenv maintainer here

based on a cursory glance at your logs and a bit of googling, it looks like `pycrypto` is trying to link against headers in `/usr/include/_stdio.h` which I'm _guessing_ isn't correct, not sure whether this is because of some flags we are setting in pipenv or because of an issue with OSX or some other thing, but you may want to check out [this comment](https://github.com/SOHU-Co/kafka-node/issues/881#issuecomment-377109841) in particular, and the whole thread in general, to see if any of it pertains to you.

I don't use OSX and have no specific details, but in general it seems like at least sometimes, this type of issue selects for users who have recently restored from a 'time machine' or something like that? But also homebrew might be involved, I'm not sure.  The thread might just make more sense to you

**Comment by ewdurbin** [comment]
No longer using pipenv, closing as stale.
